### ISSUE TITLE
용민이의 ToyStroy

### ISSUE THREAD

**Issue by CodeJugller** [MetaMonkey-studyteam/Hw_proj#5]
#### Description
장난감 온라인 쇼핑몰 구현 

#### Files
toystory.jsp

#### Tasks
필요한 순서대로 작업을 서술해주세요
- [x] 장난감 온라인 쇼핑몰에 필요한 상품 등록
- [x] 다른 상품과 중복 선택이 가능하게 구현
- [x] 지불할 금액과 구매 선택 시 post요청 하도록 구현
